-- 코드를 입력하세요
SELECT O.CAR_ID, O.CAR_TYPE,
       ROUND(O.DAILY_FEE * (100 - P.DISCOUNT_RATE)/100, 0) * 30 AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
LEFT JOIN (SELECT CAR_ID, 
        MAX(START_DATE) AS START, 
        MAX(END_DATE) AS END
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID) AS B
ON A.CAR_ID = B.CAR_ID
WHERE (B.END < '2022-11-01' OR B.END IS NULL) 
       AND (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')) AS O
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON O.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE 500000 <= ROUND(O.DAILY_FEE * (100 - P.DISCOUNT_RATE)/100, 0) * 30
     AND ROUND(O.DAILY_FEE * (100 - P.DISCOUNT_RATE)/100, 0) * 30 < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;

