SELECT R.CAR_ID, R.CAR_TYPE, 
       ROUND(R.DAILY_FEE * 30 * (100- P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM
(
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    JOIN 
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        HAVING MAX(END_DATE) < '2022-11-01'
    ) AS B
    ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV'
) AS R
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON R.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상' 
AND 500000 <= ROUND(R.DAILY_FEE * 30 * (100- P.DISCOUNT_RATE) / 100, 0) 
AND ROUND(R.DAILY_FEE * 30 * (100- P.DISCOUNT_RATE) / 100, 0) <= 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC
