SELECT I.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE like 'Intact%' AND 
(O.SEX_UPON_OUTCOME like 'Spayed%' OR O.SEX_UPON_OUTCOME like 'Neutered%')
ORDER BY I.ANIMAL_ID