-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), 
     COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
     ROUND(COUNT(DISTINCT U.USER_ID) / 
           (SELECT COUNT(*) FROM USER_INFO AS U WHERE YEAR(U.JOINED) = 2021), 1) 
           AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY 1, 2;


