WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM CTE
    WHERE HOUR < 23
)

SELECT C.HOUR, COUNT(HOUR(A.DATETIME))
FROM CTE AS C
LEFT JOIN ANIMAL_OUTS AS A
ON C.HOUR = HOUR(A.DATETIME)
GROUP BY C.HOUR
ORDER BY C.HOUR;