SELECT A.MEMBER_NAME, B.REVIEW_TEXT,
        DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE AS A
JOIN (SELECT L.MEMBER_ID, L.REVIEW_TEXT, L.REVIEW_DATE
FROM REST_REVIEW AS L
JOIN(SELECT MEMBER_ID
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY COUNT(*) DESC
      LIMIT 1) AS R
ON L.MEMBER_ID = R.MEMBER_ID) AS B
ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY 3 ASC, 2 ASC




      