-- 코드를 입력하세요
SELECT T2.MEMBER_NAME, T1.REVIEW_TEXT, 
DATE_FORMAT(T1.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS T1
JOIN (SELECT M.MEMBER_ID, M.MEMBER_NAME
        FROM MEMBER_PROFILE AS M
        JOIN REST_REVIEW AS R
        ON M.MEMBER_ID = R.MEMBER_ID
        GROUP BY M.MEMBER_NAME
        ORDER BY COUNT(*) DESC
        LIMIT 1) AS T2
ON T1.MEMBER_ID = T2.MEMBER_ID
ORDER BY 3, 2