-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.TEMPSUM)
FROM (SELECT BOOK_ID, SUM(SALES) AS TEMPSUM
FROM BOOK_SALES
WHERE '2022-01-01' <= SALES_DATE AND SALES_DATE <= '2022-01-31'
GROUP BY BOOK_ID) AS B
JOIN BOOK AS A
ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC
