WITH RECURSIVE CTE AS(
    SELECT 0 AS PRICE
    UNION ALL
    SELECT PRICE + 10000
    FROM CTE
    WHERE PRICE < (SELECT MAX(PRICE) - 10000 FROM PRODUCT)
)

SELECT C.PRICE AS PRICE_GROUP, 
       COUNT(P.PRICE) AS PRODUCTS
FROM CTE AS C
LEFT JOIN PRODUCT AS P 
ON C.PRICE / 10000 = P.PRICE DIV 10000
GROUP BY C.PRICE
HAVING COUNT(P.PRICE) > 0
ORDER BY C.PRICE